function [trainedClassifier, validationAccuracy] = quadraticSVM(trainingData)
% trainClassifier(trainingData)
%  returns a trained classifier and its validation accuracy.
%  This code recreates the classification model trained in
%  Classification Learner app.
%
%   Input:
%       trainingData: the training data of same data type as imported
%        in the app (table or matrix).
%
%   Output:
%       trainedClassifier: a struct containing the trained classifier.
%        The struct contains various fields with information about the
%        trained classifier.
%
%       trainedClassifier.predictFcn: a function to make predictions
%        on new data. It takes an input of the same form as this training
%        code (table or matrix) and returns predictions for the response.
%        If you supply a matrix, include only the predictors columns (or
%        rows).
%
%       validationAccuracy: a double containing the validation accuracy
%        score in percent. In the app, the History list displays this
%        overall accuracy score for each model.
%
%  Use the code to train the model with new data.
%  To retrain your classifier, call the function from the command line
%  with your original data or new data as the input argument trainingData.
%
%  For example, to retrain a classifier trained with the original data set
%  T, enter:
%    [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
%  To make predictions with the returned 'trainedClassifier' on new data T,
%  use
%    yfit = trainedClassifier.predictFcn(T)
%
%  To automate training the same classifier with new data, or to learn how
%  to programmatically train classifiers, examine the generated code.

% Auto-generated by MATLAB on 13-Jul-2017 22:38:46


% Convert input to table
inputTable = table(trainingData');
inputTable.Properties.VariableNames = {'row'};

% Split matrices in the input table into vectors
inputTable.row_1 = inputTable.row(:,1);
inputTable.row_2 = inputTable.row(:,2);
inputTable.row_3 = inputTable.row(:,3);
inputTable.row_4 = inputTable.row(:,4);

% Extract predictors and response
% This code processes the data into the right shape for training the
% classifier.
predictorNames = {'row_2', 'row_3', 'row_4'};
predictors = inputTable(:, predictorNames);
response = inputTable.row_1;

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
template = templateSVM(...
    'KernelFunction', 'polynomial', ...
    'PolynomialOrder', 2, ...
    'KernelScale', 'auto', ...
    'BoxConstraint', 1, ...
    'Standardize', true);
classificationSVM = fitcecoc(...
    predictors, ...
    response, ...
    'Learners', template, ...
    'Coding', 'onevsone', ...
    'ClassNames', [1; 2; 3; 4]);

trainedClassifier.ClassificationSVM = classificationSVM;
convertMatrixToTableFcn = @(x) table(x', 'VariableNames', {'row'});
splitMatricesInTableFcn = @(t) [t(:,setdiff(t.Properties.VariableNames, {'row'})), array2table(table2array(t(:,{'row'})), 'VariableNames', {'row_2', 'row_3', 'row_4'})];
extractPredictorsFromTableFcn = @(t) t(:, predictorNames);
predictorExtractionFcn = @(x) extractPredictorsFromTableFcn(splitMatricesInTableFcn(convertMatrixToTableFcn(x)));
svmPredictFcn = @(x) predict(classificationSVM, x);
trainedClassifier.predictFcn = @(x) svmPredictFcn(predictorExtractionFcn(x));
% Convert input to table
inputTable = table(trainingData');
inputTable.Properties.VariableNames = {'row'};

% Split matrices in the input table into vectors
inputTable.row_1 = inputTable.row(:,1);
inputTable.row_2 = inputTable.row(:,2);
inputTable.row_3 = inputTable.row(:,3);
inputTable.row_4 = inputTable.row(:,4);

% Extract predictors and response
% This code processes the data into the right shape for training the
% classifier.
predictorNames = {'row_2', 'row_3', 'row_4'};
predictors = inputTable(:, predictorNames);
response = inputTable.row_1;


% Perform cross-validation
partitionedModel = crossval(trainedClassifier.ClassificationSVM, 'KFold', 5);

% Compute validation accuracy
validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');

% Compute validation predictions and scores
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);